#!/usr/bin/env bash
# tests/smoke.sh: post-install checks for pi-web on this host. Read-only apart from one
# `podman healthcheck run`. Run as the account that owns the units; scripts/install.sh and
# scripts/upgrade.sh run it after every (re)start.
#
#   tests/smoke.sh          exit 0 when every check passes
#
# Checks: the unit is active and generated by Quadlet (not shadowed); the container is
# healthy; port 30141 listens on 127.0.0.1 only; /api/home answers 200; the installed unit
# carries no literal account path; the running image is the unit's pinned tag; the host
# mounts resolve to this account; the health timer is active.
set -uo pipefail
PORT=30141
UNIT=pi-web.service
CONTAINER=pi-web
INSTALLED=$HOME/.config/containers/systemd/pi-web.container
fails=0
pass() { printf 'ok    %s\n' "$*"; }
fail() { printf 'FAIL  %s\n' "$*"; fails=$((fails + 1)); }

# 1. unit
if [[ $(systemctl --user is-active "$UNIT" 2>/dev/null) == active ]]; then pass "$UNIT is active"; else fail "$UNIT is not active"; fi
frag=$(systemctl --user show -p FragmentPath --value "$UNIT" 2>/dev/null)
if [[ $frag == */systemd/generator/* ]]; then pass "$UNIT comes from the Quadlet generator"; else fail "$UNIT is loaded from '$frag' (shadowed?)"; fi

# 2. health
if podman healthcheck run "$CONTAINER" >/dev/null 2>&1; then pass "$CONTAINER healthcheck passes"; else fail "$CONTAINER healthcheck fails"; fi

# 3. loopback-only listener
listeners=$(ss -tlnH 2>/dev/null | awk '{print $4}' | grep -E ":$PORT\$" | sort -u | tr '\n' ' ')
if [[ $listeners == "127.0.0.1:$PORT " ]]; then
  pass "port $PORT listens on 127.0.0.1 only"
else
  fail "port $PORT listeners: '${listeners:-none}' (want exactly 127.0.0.1:$PORT)"
fi

# 4. HTTP (a raw-IP Host passes pi-web's trust guard)
code=$(curl -s -o /dev/null -m 10 -w '%{http_code}' "http://127.0.0.1:$PORT/api/home" 2>/dev/null) || true
if [[ $code == 200 ]]; then pass "GET /api/home -> 200"; else fail "GET /api/home -> ${code:-000}"; fi

# 5. no literal account paths in the installed unit (%h / %t only)
if [[ -f $INSTALLED ]]; then
  # (/data/pi-agent/home is the agent's in-volume HOME, not a host path.)
  if grep -vE '^[[:space:]]*#' "$INSTALLED" | grep -qE '(^|[[:space:]=:])(/host)?/home/[A-Za-z0-9_.-]+|/run/user/[0-9]+'; then
    fail "$INSTALLED contains a literal /home/<user> or /run/user/<uid> path"
  else
    pass "installed unit uses %h/%t only"
  fi
else
  fail "$INSTALLED is missing"
fi

# 6. running image = pinned tag
pinned=$(sed -n 's/^Image=//p' "$INSTALLED" 2>/dev/null | tail -n1)
want=$(podman image inspect --format '{{.Id}}' "$pinned" 2>/dev/null || true)
have=$(podman container inspect --format '{{.Image}}' "$CONTAINER" 2>/dev/null || true)
if [[ -n $want && $want == "$have" ]]; then pass "running image is $pinned"; else fail "running image ${have:0:12} is not the pinned $pinned (${want:0:12})"; fi

# 7. host-control mounts resolve to this account
src=$(podman container inspect --format '{{range .Mounts}}{{if eq .Destination "/host'"$HOME"'"}}{{.Source}}{{end}}{{end}}' "$CONTAINER" 2>/dev/null || true)
if [[ $src == "$HOME" ]]; then pass "home bind is $HOME -> /host$HOME"; else fail "home bind source is '${src:-missing}', want $HOME"; fi
hh=$(podman container inspect --format '{{range .Config.Env}}{{println .}}{{end}}' "$CONTAINER" 2>/dev/null | sed -n 's/^HOST_HOME=//p')
if [[ $hh == "/host$HOME" ]]; then pass "HOST_HOME=/host$HOME"; else fail "HOST_HOME='${hh:-unset}', want /host$HOME"; fi

# 8. health timer
if [[ $(systemctl --user is-active pi-web-health.timer 2>/dev/null) == active ]]; then pass "pi-web-health.timer is active"; else fail "pi-web-health.timer is not active"; fi

if ((fails)); then
  echo "smoke: $fails check(s) failed"
  exit 1
fi
echo "smoke: PASS"
